#!/usr/bin/env bash

set -euxo pipefail

cd coredns

CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
  go build -o ../dist/linux/amd64/coredns

CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 \
  go build -o ../dist/linux/arm/v7/coredns

CGO_ENABLED=0 GOOS=linux GOARCH=arm64 \
  go build -o ../dist/linux/arm64/coredns
