name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: coredns-build

      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          ref: v1.10.0
          path: coredns

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Apply plugin config
        run: cp --force ./coredns-build/{.goreleaser.yaml,plugin.cfg} ./coredns

      - run: go generate coredns.go
        working-directory: ./coredns

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a git tag required by GoRelease
        run: git tag v0.0.0
        working-directory: ./coredns

      - uses: goreleaser/goreleaser-action@v3
        with:
          args: release --skip-validate
          workdir: ./coredns
