name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          ref: v1.10.0
          path: coredns

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Apply plugin config
        run: cp --force ./plugin.cfg ./coredns

      - run: go generate coredns.go
        working-directory: ./coredns

      - run: go get
        working-directory: ./coredns

      - name: go build
        run: ./go-build

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (and push)
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            ghcr.io/ciffelia/coredns:git-${{ github.sha }}
            ghcr.io/ciffelia/coredns:latest
          platforms: |
            linux/amd64
            linux/arm/v7
            linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
