name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: coredns-build

      - uses: actions/checkout@v3
        with:
          repository: coredns/coredns
          ref: v1.10.0
          path: coredns

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"

      - name: Apply plugin config
        run: cp --force ./coredns-build/plugin.cfg ./coredns/plugin.cfg

      - name: Build CoreDNS
        run: make
        working-directory: ./coredns
